export TARGETDIR=${PWD}
export H_FILE=ssl3_cbc_remove_padding.h
export C_FILE=ssl3_cbc_remove_padding.c
export O_FILE=ssl3_cbc_remove_padding.o

all:
	make -C ../../src

clean:
	rm -f *.o test
	make -C ../../src clean
