all: semantics.pdf altfact.pdf

semantics.pdf: semantics.tex
	pdflatex semantics.tex

altfact.pdf: altfact.tex
	pdflatex altfact.tex

clean:
	rm -f semantics.pdf altfact.pdf *.aux *.blg *.bbl *.log *.tmp *.xref *.idv *.4og *.4ct *.lg *.4tc *~

